# Generated by Django 3.1.1 on 2020-09-29 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='capacity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='tickettypeseat',
            name='id',
        ),
        migrations.AlterField(
            model_name='tickettypeseat',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tickets.seat'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='events',
            field=models.ManyToManyField(related_name='venues', through='tickets.Date', to='tickets.Event'),
        ),
    ]
