# Generated by Django 3.1.1 on 2020-10-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TIMEDOUT', 'Timedout'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='state',
            field=models.CharField(choices=[('GOOD', 'Good'), ('WEARY', 'Weary'), ('BROKEN', 'Broken')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettypeseat',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=20),
        ),
    ]
