# Generated by Django 3.1.1 on 2020-10-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20201024_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('number', 'row', 'section')},
        ),
    ]
