# Generated by Django 3.1.1 on 2020-10-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201024_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('date', 'slug')},
        ),
    ]
