# Generated by Django 3.1.1 on 2020-10-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201025_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='tickettypeseat',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='last_saved',
            new_name='last_modified',
        ),
        migrations.RemoveField(
            model_name='tickettypeseat',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='tickettypeseat',
            name='tickettype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickettype_seats', to='tickets.tickettype'),
            preserve_default=False,
        ),
    ]
